### ISSUE TITLE
Contra sprite movement

### ISSUE THREAD

**Issue by mdd45** [jotego/jtcontra#1]
there is a gfx bug on the way the enemy is moving. best discribed here:

https://www.youtube.com/watch?v=uBryUbPGScg after 6:11

**Comment by jotego** [comment]
After seeing the video I wonder if that is an artefact of the HDMI capturer. The flashing characters for the second player are not correctly displayed either. The hardware flashes these objects very quickly and the HDMI signal chain seems to be missing it.
I'll play the same MRA version tomorrow to double check it on my screen.

**Comment by jotego** [comment]
Amoore has confirmed that CRT video is correct. This is a HDMI signal chain artefact that would occur with the original board too.

**Comment by mdd45** [comment]
you are right, i just tested it and it seems fine indeed
