### ISSUE TITLE
Low HSync rate

### ISSUE THREAD

**Issue by misteraddons** [jotego/jtcontra#7]
Discovered while testing on a real arcade cabinet, the hsync rate is 15.15 kHz, which makes some monitors grumpy. Is it possible to bump it up closer to 15.6 kHz? Thanks :)

**Comment by jotego** [comment]
I measured it on my PCB and designed it to match it. But the oscillator on the PCB might have drifted after so many years.
When Furrtek finishes tracing the K007121, the exact frequency will be clear. He says he's at 90% now with this task. So I'd rather wait for him.

**Comment by jotego** [comment]
I'm not completely convinced, but it looks like the line period is 64us in the original counter. I'm updating it to that frequency
