### ISSUE TITLE
JTContra - Screen titlte and credit are shifted to the bottom

### ISSUE THREAD

**Issue by wwark** [jotego/jtcontra#8]
With the last version 20210520, the screen titlte and credit are shifted to the bottom
![NODATE-screen_0001](https://user-images.githubusercontent.com/469461/119081081-8d17a900-b9fb-11eb-96ce-fd78232cd8b0.png)
![NODATE-screen_0002](https://user-images.githubusercontent.com/469461/119081086-8f7a0300-b9fb-11eb-990c-d33368da3f9f.png)
Thanks,

**Comment by paulb-nl** [comment]
If Mame is correct then the height should be 224px instead of 240px. There are also 2 pixel columns missing on the right:

JT:
![20210521_170628-screen](https://user-images.githubusercontent.com/2227984/119175609-50cf6180-ba6a-11eb-96ad-103e9523b322.png)

Mame:
![mame_contra](https://user-images.githubusercontent.com/2227984/119175636-5af16000-ba6a-11eb-8473-dd832eeae7db.png)

**Comment by jotego** [comment]
MAME treats games having the K007121 as though they didn't share hardware, so you can get a very different impression about it. That's where the screen resolution report differences come from.

About the two missing pixels, it took a while to make them appear, I thought I had them but then they went lost again in the final commit. I was just too tired to look at it again. In some of the not-so-old commits you can see them.

If you try to fix this, be aware that there is a commit with a VS setting that doesn't work in MiSTer at all (it worked on MiST only).

**Comment by M-Walrus** [comment]
This is effecting Trick Trap/Labyrinth Runner also.  The bottom row (maybe two?) of the image is clearly cut off on both HDMI and CRT, on MiSTer.

**Comment by jotego** [comment]
The missing pixels are fixed in 3de230e
About removing the top blank row, we can follow the conversation in #10

**Comment by wwark** [comment]
Thanks @paulb-nl  and @jotego  I confirmed it fixed the credit part !
